"""init system table

Revision ID: 2db4e2d13e0e
Revises: 
Create Date: 2025-03-11 11:44:29.303802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db4e2d13e0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='账号ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('password_salt', sa.String(length=255), nullable=True, comment='密码加盐'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头衔'),
    sa.Column('interface_language', sa.String(length=255), nullable=True, comment='语言'),
    sa.Column('interface_theme', sa.String(length=255), nullable=True, comment='主题'),
    sa.Column('timezone', sa.String(length=255), nullable=True, comment='时区'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近一次登录时间'),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True, comment='最近一次登录IP'),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='最近一次激活时间'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False, comment='账号状态'),
    sa.Column('initialized_at', sa.DateTime(), nullable=True, comment='初始化日期'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey')),
    comment='账号信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_config',
    sa.Column('config_id', sa.BigInteger(), nullable=False, comment='参数主键'),
    sa.Column('config_name', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='参数名称'),
    sa.Column('config_key', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='参数键名'),
    sa.Column('config_value', sa.String(length=500), server_default=sa.FetchedValue(), nullable=True, comment='参数键值'),
    sa.Column('config_type', sa.String(length=1), server_default=sa.FetchedValue(), nullable=True, comment='系统内置（Y是 N否）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='更新者'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('config_id', name=op.f('sys_config_pkey')),
    comment='系统配置表',
    mysql_charset='utf8'
    )
    op.create_table('sys_dict_data',
    sa.Column('dict_code', sa.BigInteger(), nullable=False, comment='字典编码'),
    sa.Column('dict_sort', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='字典排序'),
    sa.Column('dict_label', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='字典标签'),
    sa.Column('dict_value', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='字典键值'),
    sa.Column('dict_type', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='字典类型'),
    sa.Column('css_class', sa.String(length=100), nullable=True, comment='样式属性（其他样式扩展）'),
    sa.Column('list_class', sa.String(length=100), nullable=True, comment='表格回显样式'),
    sa.Column('is_default', sa.String(length=1), server_default=sa.FetchedValue(), nullable=True, comment='是否默认（Y是 N否）'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='更新者'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dict_code', name=op.f('sys_dict_data_pkey')),
    comment='系统字典数据表',
    mysql_charset='utf8'
    )
    with op.batch_alter_table('sys_dict_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sys_dict_data_dict_type_idx'), ['dict_type'], unique=False)

    op.create_table('sys_dict_type',
    sa.Column('dict_id', sa.BigInteger(), nullable=False, comment='字典主键'),
    sa.Column('dict_name', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=100), server_default=sa.FetchedValue(), nullable=True, comment='字典类型'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='状态（0正常 1停用）'),
    sa.Column('create_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=64), server_default=sa.FetchedValue(), nullable=True, comment='更新者'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dict_id', name=op.f('sys_dict_type_pkey')),
    sa.UniqueConstraint('dict_type', name=op.f('sys_dict_type_dict_type_key')),
    comment='字典类型表',
    mysql_charset='utf8'
    )
    op.create_table('sys_online',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('ip', sa.String(length=100), nullable=True, comment='登录IP'),
    sa.Column('login_name', sa.String(length=100), nullable=True, comment='登录名'),
    sa.Column('type', sa.Integer(), nullable=True, comment='类型'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_online_pkey')),
    comment='用户在线信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_organization',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('organization_id', sa.BigInteger(), nullable=True, comment='机构ID'),
    sa.Column('code', sa.String(length=200), nullable=True, comment='机构编码'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='机构名称'),
    sa.Column('seq', sa.Integer(), nullable=True, comment='序号'),
    sa.Column('leader', sa.String(length=20), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='地址'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_organization_pkey')),
    comment='机构信息表',
    mysql_charset='utf8'
    )
    with op.batch_alter_table('sys_organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sys_organization_organization_id_idx'), ['organization_id'], unique=False)

    op.create_table('sys_organization_resource',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('resource_id', sa.String(length=36), nullable=False, comment='资源ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_organization_resource_pkey')),
    comment='机构资源关联表',
    mysql_charset='utf8'
    )
    op.create_table('sys_resource',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='资源ID'),
    sa.Column('resource_type_id', sa.BigInteger(), nullable=True, comment='资源类型ID'),
    sa.Column('seq', sa.Integer(), nullable=True, comment='序号'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('target', sa.String(length=100), nullable=True, comment='目标'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路径'),
    sa.Column('url', sa.String(length=200), nullable=True, comment='URL'),
    sa.Column('perms', sa.String(length=100), nullable=True, comment='权限标识'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_resource_pkey')),
    comment='资源信息表',
    mysql_charset='utf8'
    )
    with op.batch_alter_table('sys_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sys_resource_resource_id_idx'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('sys_resource_resource_type_id_idx'), ['resource_type_id'], unique=False)

    op.create_table('sys_resource_type',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='资源名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='资源描述'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_resource_type_pkey')),
    comment='资源类型表',
    mysql_charset='utf8'
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('seq', sa.Integer(), nullable=True, comment='序号'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('role_key', sa.String(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('data_scope', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='角色状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_role_pkey')),
    comment='角色信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_role_organization',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_role_organization_pkey')),
    comment='角色机构关联表',
    mysql_charset='utf8'
    )
    op.create_table('sys_role_resource',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('resource_id', sa.String(length=36), nullable=False, comment='资源ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_role_resource_pkey')),
    comment='角色资源关联表',
    mysql_charset='utf8'
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('login_name', sa.String(length=100), nullable=False, comment='登录名'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='密码'),
    sa.Column('photo', sa.String(length=200), nullable=True, comment='照片'),
    sa.Column('sex', sa.Integer(), nullable=True, comment='性别'),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='年龄'),
    sa.Column('email', sa.String(length=50), server_default=sa.FetchedValue(), nullable=True, comment='用户邮箱'),
    sa.Column('phone', sa.String(length=11), server_default=sa.FetchedValue(), nullable=True, comment='手机号码'),
    sa.Column('employ_date', sa.DateTime(), nullable=True, comment='雇佣日期'),
    sa.Column('status', sa.Integer(), server_default=sa.FetchedValue(), nullable=True, comment='用户状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_pkey')),
    sa.UniqueConstraint('login_name', name=op.f('sys_user_login_name_key')),
    comment='用户信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_user_organization',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_organization_pkey')),
    comment='用户机构关联表',
    mysql_charset='utf8'
    )
    op.create_table('sys_user_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_role_pkey')),
    comment='用户角色关联表',
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_organization')
    op.drop_table('sys_user')
    op.drop_table('sys_role_resource')
    op.drop_table('sys_role_organization')
    op.drop_table('sys_role')
    op.drop_table('sys_resource_type')
    with op.batch_alter_table('sys_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sys_resource_resource_type_id_idx'))
        batch_op.drop_index(batch_op.f('sys_resource_resource_id_idx'))

    op.drop_table('sys_resource')
    op.drop_table('sys_organization_resource')
    with op.batch_alter_table('sys_organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sys_organization_organization_id_idx'))

    op.drop_table('sys_organization')
    op.drop_table('sys_online')
    op.drop_table('sys_dict_type')
    with op.batch_alter_table('sys_dict_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sys_dict_data_dict_type_idx'))

    op.drop_table('sys_dict_data')
    op.drop_table('sys_config')
    op.drop_table('account')
    # ### end Alembic commands ###
