"""init table

Revision ID: dc89c3e002f5
Revises: 
Create Date: 2025-03-12 19:28:35.544238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc89c3e002f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门ID'),
    sa.Column('org_id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('order', sa.SmallInteger(), nullable=False, comment='排序'),
    sa.Column('desc', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_dept_pkey')),
    comment='部门信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_menu',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='菜单名称'),
    sa.Column('menu_type', sa.String(length=16), nullable=False, comment='菜单类型'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='菜单图标'),
    sa.Column('path', sa.String(length=100), nullable=True, comment='菜单路径'),
    sa.Column('order', sa.SmallInteger(), nullable=False, comment='排序'),
    sa.Column('remark', sa.JSON(), nullable=True, comment='备注'),
    sa.Column('is_hidden', sa.Boolean(), nullable=True, comment='是否隐藏'),
    sa.Column('component', sa.String(length=100), nullable=True, comment='组件'),
    sa.Column('keepalive', sa.Boolean(), nullable=True, comment='存活'),
    sa.Column('redirect', sa.String(length=100), nullable=True, comment='重定向'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_menu_pkey')),
    comment='菜单信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_organization',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='机构名称'),
    sa.Column('leader', sa.String(length=20), nullable=True, comment='机构负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='机构地址'),
    sa.Column('status', sa.Integer(), nullable=True, comment='机构状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_organization_pkey')),
    comment='机构信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('desc', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_role_pkey')),
    comment='角色信息表',
    mysql_charset='utf8'
    )
    op.create_table('sys_role_menu',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_role_menu_pkey')),
    comment='角色菜单关联表',
    mysql_charset='utf8'
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('alias', sa.String(length=100), nullable=True, comment='用户昵称'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('password_salt', sa.String(length=255), nullable=False, comment='密码加盐'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号码'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='用户邮箱'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('sex', sa.Integer(), nullable=True, comment='性别'),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='年龄'),
    sa.Column('tenant_code', sa.String(length=8), nullable=False, comment='租户CODE'),
    sa.Column('org_id', sa.BigInteger(), nullable=False, comment='机构ID'),
    sa.Column('dept_id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否为超级管理员'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近一次登录时间'),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True, comment='最近一次登录IP'),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='最近一次激活时间'),
    sa.Column('user_status', sa.String(length=16), nullable=False, comment='用户状态'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_pkey')),
    sa.UniqueConstraint('username', name=op.f('sys_user_username_key')),
    comment='用户表',
    mysql_charset='utf8'
    )
    op.create_table('sys_user_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_role_pkey')),
    comment='用户角色关联表',
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user')
    op.drop_table('sys_role_menu')
    op.drop_table('sys_role')
    op.drop_table('sys_organization')
    op.drop_table('sys_menu')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
